### PR TITLE
fix: preserve tag casing

### LINKED ISSUE #189: Why normalize `type` and `tag` to lowercase?
Thank for making such a great tool.

This is not a bug. I'm just curious why we need to normalize `type` and `tag` to lowercase.

https://github.com/unjs/consola/blob/5619fc7cfb8eda48ce4471db625fab2bf39c1ad9/src/consola.ts#L299-L303

### PR DESCRIPTION
**Pull request by jsonleex**
resolves #189

### CODE REVIEW

File: src/consola.ts [hunk 1]
```diff
@@ -296,11 +296,10 @@ export class Consola {
       delete logObj.additional;
     }
 
-    // Normalize type and tag to lowercase
+    // Normalize type to lowercase
     logObj.type = (
       typeof logObj.type === "string" ? logObj.type.toLowerCase() : "log"
     ) as LogType;
-    logObj.tag = typeof logObj.tag === "string" ? logObj.tag.toLowerCase() : "";
```
Comment (NozomuIkuta) [inline src/consola.ts:303]: I'm not so familiar with the Consola implementation, but I guess fallback to empty string should be kept 🤔 

```ts
logObj.tag = typeof logObj.tag === "string" ? logObj.tag : "";
```

Comment (jsonleex) [reply src/consola.ts:303]: My bad, I will fix this, thanks.

**Review by pi0 — COMMENTED** [review]
Thanks!
