### PR TITLE
fix: make box title color same as border

### LINKED ISSUE #230: box title should have same color as border

### PR DESCRIPTION
**Pull request by NozomuIkuta**
### 🔗 Linked issue

#230

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #230

Question: it seems that `code` in title is colored differently.
Should I override the color or is it fine?
If I should, I will add explanation to README.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/utils/box.ts [hunk 1]
```diff
@@ -259,6 +259,7 @@ export function box(text: string, _opts: BoxOpts = {}) {
   }
   // Include the title if it exists with borders
   if (opts.title) {
+    const title = _color ? _color(opts.title) : opts.title;
```
Comment (NozomuIkuta) [inline src/utils/box.ts:262]: Although I followed other part of the code base, there seems no such case where `_color` is falsy in terms of type definition of `getColor` function and its actual code as far as I checked.
If it's not intentional for some reasons, I will fix it as well.

https://github.com/unjs/consola/blob/35c9d6ea45ef60faaabb2a34cc60fdc621cf7730/src/utils/box.ts#L228-L243

Comment (pi0) [reply src/utils/box.ts:262]: Indeed. recent implementation of `getColor` had fallback.

Feel free to make another PR to refactor

**Review by pi0 — APPROVED** [review]
